services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - JWT_SECRET=test-secret-key-for-testing
      - MONGODB_URI=mongodb://test:test@mongodb-test:27017/test?authSource=admin
      - REDIS_URL=redis://redis-test:6379
    command: npm test
    depends_on:
      mongodb-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy

  app-test-watch:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - JWT_SECRET=test-secret-key-for-testing
      - MONGODB_URI=mongodb://test:test@mongodb-test:27017/test?authSource=admin
      - REDIS_URL=redis://redis-test:6379
    command: npm run test:watch
    depends_on:
      mongodb-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy

  app-test-coverage:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - JWT_SECRET=test-secret-key-for-testing
      - MONGODB_URI=mongodb://test:test@mongodb-test:27017/test?authSource=admin
      - REDIS_URL=redis://redis-test:6379
    command: npm run test:coverage
    depends_on:
      mongodb-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy

  mongodb-test:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - "27018:27017"
    volumes:
      - mongodb_test_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_test_data:
  redis_test_data:
